version: "3.7"

services: 
  database_hubspot_tmp:
    image: postgres
    container_name: database_hubspot_tmp
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hubspot
      - POSTGRES_DB=hubspot_tmp_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: hubspot_template
    ports:
      - 3333:3333
    volumes:
      - .:/usr/hubspot
    network_mode: host

volumes:
  pgdata:
    driver: local
