version: "3.7"

services:
  rentx_database:
    image: "postgres:14"
    container_name: rentx_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "adm_rentx"
      POSTGRES_PASSWORD: "rentx_password"
      POSTGRES_DB: "rentx"
    volumes:
      - pgdata:/var/lib/postgres/data
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/rentx
    links:
      - rentx_database
    depends_on: 
      - rentx_database

volumes:
  pgdata:
    driver: local